-- 코드를 입력하세요
SELECT HISTORY_ID, 
    CAR_ID, 
    DATE_FORMAT(START_DATE,'%Y-%m-%d') as START_DATE, 
    DATE_FORMAT(END_DATE,'%Y-%m-%d') as END_DATE,
        CASE WHEN DATE_FORMAT(DATE_ADD(START_DATE, INTERVAL 29 DAY),'%Y-%m-%d') <= END_DATE
            THEN '장기 대여' 
            ELSE '단기 대여'
            END AS RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE DATE_FORMAT(START_DATE,'%Y%m') = '202209'
ORDER BY HISTORY_ID DESC;